version: "3.3"
services:
  speedtest:
    image: openspeedtest/latest:v2.0.6
    restart: unless-stopped
    container_name: openspeedtest
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "3000:3000"
      - "3001:3001"
