version: "3.3"
services:
  speedtest:
    image: openspeedtest/latest:v2.0.6
    restart: unless-stopped
    container_name: openspeedtest
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openspeedtest.rule=Host(`openspeedtest.oskarrosen.io`)"
      - "traefik.http.routers.openspeedtest.entrypoints=web"
      - "traefik.http.services.openspeedtest.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_internal"
    networks:
      - default
      - traefik_internal
    ports:
      - "3000:3000"
      - "3001:3001"

networks:
  traefik_internal:
    external: true
