version: "3.3"
services:
  healthcheck:
    restart: unless-stopped
    container_name: healthcheck
    build: .
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.healthcheck.rule=Host(`healthcheck.oskarrosen.io`)"
      - "traefik.http.routers.healthcheck.entrypoints=web,web_secure"
      - "traefik.http.routers.healthcheck.tls=true"
      - "traefik.http.routers.healthcheck.tls.certresolver=lets_encrypt"
      - "traefik.http.services.healthcheck.loadbalancer.server.port=8080"
      - "traefik.http.routers.healthcheck-www.rule=Host(`www.oskarrosen.io`)"
      - "traefik.http.routers.healthcheck-www.entrypoints=web_secure"
      - "traefik.http.routers.healthcheck-www.service=healthcheck"
      - "traefik.http.routers.healthcheck-www.tls=true"
      - "traefik.http.routers.healthcheck-www.tls.certresolver=lets_encrypt"
      - "traefik.http.routers.healthcheck-www.tls.domains[0].main=*.oskarrosen.io"
      - "traefik.docker.network=traefik_internal"
    networks:
      - default
      - traefik_internal
    ports:
      - "8086:8080"

networks:
  traefik_internal:
    external: true
