version: "3.3"
services:
  healthcheck:
    restart: unless-stopped
    container_name: healthcheck
    build: .
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "8086:8080"
