http:
  middlewares:
    ratelimit:
      rateLimit:
        average: 100
        period: 1s
        burst: 50

    fail2ban:
      plugin:
        fail2ban:
          rules:
            bantime: "3h"
            findtime: "10m"
            maxretry: 4
            statuscode: "400,401,403-499"
